version: '3.9'

services:
  app:
    build: ./docker
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
      - ~/.ssh:/home/web/.ssh
    networks:
      - app
    depends_on:
        - mysql

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-pass}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE:-db}'
      MYSQL_USER: '${DB_USERNAME:-user}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-pass}'
    volumes:
      - 'mysql:/var/lib/mysql'
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  mysql:
    driver: local